export interface PriorityDistrict {
  state: string;
  district: string;
}

export const priorityDistricts: PriorityDistrict[] = [
  { state: "Madhya Pradesh", district: "Indore" },
  { state: "Madhya Pradesh", district: "Bhopal" },
  { state: "Madhya Pradesh", district: "Ujjain" },
  { state: "Madhya Pradesh", district: "Dewas" },
  { state: "Madhya Pradesh", district: "Dhar" },
  { state: "Punjab", district: "Ludhiana" },
  { state: "Punjab", district: "Amritsar" },
  { state: "Haryana", district: "Karnal" },
  { state: "Haryana", district: "Ambala" },
  { state: "Uttar Pradesh", district: "Meerut" },
  { state: "Uttar Pradesh", district: "Lucknow" },
  { state: "Uttar Pradesh", district: "Agra" },
  { state: "Uttar Pradesh", district: "Varanasi" },
  { state: "Bihar", district: "Patna" },
  { state: "Bihar", district: "Muzaffarpur" },
  { state: "Maharashtra", district: "Nashik" },
  { state: "Maharashtra", district: "Pune" },
  { state: "Maharashtra", district: "Nagpur" },
  { state: "Maharashtra", district: "Jalgaon" },
  { state: "Andhra Pradesh", district: "Guntur" },
  { state: "Andhra Pradesh", district: "Krishna" },
  { state: "Tamil Nadu", district: "Coimbatore" },
  { state: "Tamil Nadu", district: "Salem" },
  { state: "Karnataka", district: "Mandya" },
  { state: "Karnataka", district: "Belagavi" },
  { state: "Kerala", district: "Thrissur" },
  { state: "Kerala", district: "Palakkad" },
  { state: "Gujarat", district: "Rajkot" },
  { state: "Gujarat", district: "Junagadh" },
  { state: "Gujarat", district: "Anand" },
  { state: "Rajasthan", district: "Sri Ganganagar" },
  { state: "Rajasthan", district: "Kota" },
  { state: "Rajasthan", district: "Alwar" },
  { state: "West Bengal", district: "Burdwan" },
  { state: "West Bengal", district: "Hooghly" },
  { state: "Odisha", district: "Cuttack" },
  { state: "Odisha", district: "Balasore" },
  { state: "Chhattisgarh", district: "Raipur" },
  { state: "Chhattisgarh", district: "Bastar" },
  { state: "Jharkhand", district: "Ranchi" },
  { state: "Jharkhand", district: "Hazaribagh" },
  { state: "Telangana", district: "Karimnagar" },
  { state: "Telangana", district: "Warangal" },
  { state: "Jammu and Kashmir", district: "Jammu" },
  { state: "Jammu and Kashmir", district: "Srinagar" },
  { state: "Uttarakhand", district: "Dehradun" },
  { state: "Uttarakhand", district: "Haridwar" },
  { state: "Himachal Pradesh", district: "Shimla" },
  { state: "Himachal Pradesh", district: "Kangra" },
  { state: "Assam", district: "Kamrup" },
];
